---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

verifier:
  name: inspec
suites:
  - name: default
    run_list:
      - recipe[tdd::default]
    attributes:
    inspec_tests:
      - /test/integration/default
